# Generated by Django 3.2.8 on 2021-12-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='admin', max_length=10)),
                ('last_name', models.CharField(default='admin', max_length=10)),
                ('address', models.CharField(default='Delhi', max_length=50)),
                ('pincode', models.IntegerField(default=123434)),
            ],
        ),
    ]
